/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/order': RouteRecordInfo<
      '/admin/order',
      '/admin/order',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/product': RouteRecordInfo<
      '/admin/product',
      '/admin/product',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact': RouteRecordInfo<
      '/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/disaster': RouteRecordInfo<
      '/disaster',
      '/disaster',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game': RouteRecordInfo<
      '/game',
      '/game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide': RouteRecordInfo<
      '/guide',
      '/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/map': RouteRecordInfo<
      '/map',
      '/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/news': RouteRecordInfo<
      '/news',
      '/news',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/product/[id]': RouteRecordInfo<
      '/product/[id]',
      '/product/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shop': RouteRecordInfo<
      '/shop',
      '/shop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/cart': RouteRecordInfo<
      '/user/cart',
      '/user/cart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/order': RouteRecordInfo<
      '/user/order',
      '/user/order',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/order.vue': {
      routes:
        | '/admin/order'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/product.vue': {
      routes:
        | '/admin/product'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/contact.vue': {
      routes:
        | '/contact'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/disaster.vue': {
      routes:
        | '/disaster'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game.vue': {
      routes:
        | '/game'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide.vue': {
      routes:
        | '/guide'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/map.vue': {
      routes:
        | '/map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/news.vue': {
      routes:
        | '/news'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/product/[id].vue': {
      routes:
        | '/product/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/shop.vue': {
      routes:
        | '/shop'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/cart.vue': {
      routes:
        | '/user/cart'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/order.vue': {
      routes:
        | '/user/order'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
